import React, { useEffect, useState } from 'react';
import axios from 'axios';

function StudentIdCard() {
  const [profile, setProfile] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    axios.get('/api/auth/profile')
      .then(res => {
        if (res.data.success) {
          setProfile(res.data.profile);
        }
      })
      .catch(() => {
        // Fallback mock
        setProfile({
          first_name: "Amit",
          last_name: "Kumar",
          enrollment_no: "STU2026001",
          course_name: "BCA",
          dept_name: "Computer Applications",
          semester: 1,
          phone: "9812345678",
          email: "student@college.com",
          qr_code_path: "/uploads/qrcodes/STU2026001.png"
        });
      })
      .finally(() => setLoading(false));
  }, []);

  if (loading || !profile) {
    return (
      <div className="spinner-container"><div className="cms-spinner"></div></div>
    );
  }

  return (
    <div className="container py-4 fade-in-up d-flex flex-column align-items-center">
      <h2 className="fw-bold mb-4 text-center">My Digital Student ID Card</h2>
      
      {/* Real CSS styled ID Card */}
      <div
        className="card shadow-lg p-3 text-white border-0"
        style={{
          width: '380px',
          borderRadius: '16px',
          background: 'linear-gradient(135deg, #1e3a8a 0%, #0f172a 100%)',
          minHeight: '520px',
          fontFamily: "'Inter', sans-serif"
        }}
      >
        {/* Header */}
        <div className="text-center border-bottom pb-2 border-secondary mb-3">
          <h5 className="fw-bold tracking-wide mb-0">APEX INSTITUTE</h5>
          <small className="text-muted small uppercase">Digital Student Credential</small>
        </div>

        {/* Profile photo fallback/graphic */}
        <div className="d-flex justify-content-center mb-3">
          <div
            className="bg-white rounded-circle d-flex align-items-center justify-content-center text-primary fs-2 border border-secondary"
            style={{ width: '100px', height: '100px' }}
          >
            👤
          </div>
        </div>

        {/* Name and enrollment */}
        <div className="text-center mb-3">
          <h4 className="fw-bold mb-1">{profile.first_name} {profile.last_name}</h4>
          <span className="badge bg-light text-dark">{profile.enrollment_no}</span>
        </div>

        {/* Credentials metadata */}
        <div className="px-3 small mb-4">
          <div className="d-flex justify-content-between mb-1">
            <span className="text-muted">Program:</span>
            <span className="fw-semibold">{profile.course_name || 'BCA'}</span>
          </div>
          <div className="d-flex justify-content-between mb-1">
            <span className="text-muted">Semester:</span>
            <span className="fw-semibold">Semester {profile.semester}</span>
          </div>
          <div className="d-flex justify-content-between mb-1">
            <span className="text-muted">Contact:</span>
            <span className="fw-semibold">{profile.phone}</span>
          </div>
        </div>

        {/* QR Code image generated by Node server */}
        <div className="d-flex flex-column align-items-center mt-auto border-top pt-3 border-secondary">
          {profile.qr_code_path ? (
            <img
              src={`http://localhost:5000${profile.qr_code_path}`}
              alt="Student QR Verification Card"
              className="img-fluid bg-white p-2 rounded"
              style={{ width: '120px', height: '120px' }}
              onError={(e) => {
                // If backend local file path is not online yet, show dynamic placeholder
                e.target.src = `https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${profile.enrollment_no}`;
              }}
            />
          ) : (
            <div className="bg-white text-dark p-3 rounded text-center small" style={{ width: '120px', height: '120px' }}>
              QR Code Pending
            </div>
          )}
          <small className="text-muted small mt-2 uppercase tracking-widest text-center" style={{ fontSize: '10px' }}>
            SCAN FOR VERIFICATION
          </small>
        </div>
      </div>
    </div>
  );
}

export default StudentIdCard;
